variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  HARBOR_REGISTRY_HOST: laus.fzi.de:8201
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH
  HARBOR_IMAGE_NAME: $HARBOR_REGISTRY_HOST/$CI_PROJECT_PATH
  MAVEN_CLI_OPTS: -DskipTests --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  GIT_REPO_ORIGIN: ssh://git@ipe-wim-gitlab.fzi.de:2222
  GIT_STRATEGY: clone

stages:
  - build

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - mvn clean package -DskipTests
    - mvn deploy






